[Issue 927] add canonical tags on pdp plp cms page and homepage
scandipwa/base-theme pull request #1021
Opened 2020-09-23 09:27 UTC by ejnshtein

2020-09-25 13:54 UTC, yeegor requested changes
If a store code is present in the url, the canonical urls are invalid... 
Or am I wrong?
![image](https://user-images.githubusercontent.com/46347627/94275519-bb69e500-ff4f-11ea-935d-89964ba8b0cd.png)

2020-09-25 14:39 UTC, ejnshtein commented
Yep, looks like that incorrect behavior.
Working on that.

2020-09-25 15:04 UTC, ejnshtein commented
Looks like Magento do not respect store code in URL for canonical tags and returns canonical URL without store code.
<img width="286" alt="Screenshot 2020-09-25 at 18 03 13" src="https://user-images.githubusercontent.com/18352350/94283204-6337e080-ff59-11ea-81e4-ae6a11b352ae.png">

2020-09-25 15:16 UTC, ejnshtein commented
Should work now.

2020-09-28 08:03 UTC, yeegor requested changes
Consider sticking to the pattern used throughout the application and use `appendWithStoreCode` from `'Util/Url'`

2020-09-28 08:10 UTC, ejnshtein commented
Okay

2020-09-28 12:49 UTC, yeegor requested changes
I believe that double slash (`//default`) here makes the URL invalid. In both PDP and PLP.

![image](https://user-images.githubusercontent.com/46347627/94434208-14c95280-01a2-11eb-9a9d-8cb63c873587.png)

![image](https://user-images.githubusercontent.com/46347627/94434226-1bf06080-01a2-11eb-8f13-9f1893106682.png)

2020-09-28 14:26 UTC, yeegor approved these changes
Seems OK.

2020-09-28 14:26 UTC, merged