Fix header padding for all pages
scandipwa/base-theme pull request #1320
Opened 2020-09-24 12:43 UTC by drc0

When the breadcrumb is hidden all pages were going under the header, instead of fixing the margin for
each of them and worring about the breadcrumb being displayed or not, move the margin handing in the header
itself

2020-10-01 09:20 UTC, yeegor requested changes
Thank you for your contribution!
Nevertheless, minor coding style changes are required.
We look forward to hearing from you!

2020-10-01 09:20 UTC, yeegor commented on src/app/component/Header/Header.component.js
> +            <section block="Headerwrapper">
Please use BEM for this. E.g. `Header-Wrapper`

2020-10-01 09:20 UTC, yeegor commented on src/app/component/Header/Header.style.scss
> +.Headerwrapper {
Also here

2020-10-01 20:25 UTC, drc0 commented
> Thank you for your contribution!
> Nevertheless, minor coding style changes are required.
> We look forward to hearing from you!

than for your comment, see updated pull request.

2020-10-09 16:46 UTC, alfredsgenkins commented
Great job! @all-contributors please add @drc0 for code, bug!

2020-10-09 16:47 UTC, merged

2020-10-09 16:49 UTC, drc0 commented
really appreciated!