hiding 'as low as' if all variant prices are same
scandipwa/base-theme pull request #1376
Opened 2020-10-05 14:00 UTC by alex-vo

2020-10-06 12:25 UTC, alfredsgenkins requested changes

2020-10-06 12:25 UTC, alfredsgenkins commented on src/app/component/ProductActions/ProductActions.component.js
> +            return !variants.some((variant) => JSON.stringify(variant.price_range.minimum_price.final_price)
Please use destruction of properties.

2020-10-06 12:25 UTC, alfredsgenkins commented on src/app/component/ProductActions/ProductActions.component.js
> +                !== JSON.stringify(variants[0].price_range.minimum_price.final_price));
Do not break expressions & operators on to the next line :) There must be a better way!

2020-10-07 13:37 UTC, alex-vo commented
Fixed [#1006 ]

2020-10-09 12:28 UTC, alfredsgenkins approved these changes

2020-10-09 12:59 UTC, alfredsgenkins requested changes
This only patches behavior on PDP, and does not on PLP. Please implement fixes for PLP as well.

2020-10-13 12:02 UTC, alex-vo commented
See also https://github.com/scandipwa/catalog-graphql/pull/69.

2020-10-16 08:21 UTC, alfredsgenkins approved these changes

2020-10-16 08:21 UTC, alfredsgenkins commented
This one is approved, BE needs one more check + after BE merge and release the composer version bump will be required.

2020-10-20 10:57 UTC, alfredsgenkins commented
Closing, I do not think this calculation must be done on FE.

2020-10-20 10:57 UTC, closed without merging