SWPWA-1390 - Footer redesign
scandipwa/base-theme pull request #1416
Opened 2020-10-12 14:11 UTC by robertsbriedis

#1390

2020-10-26 15:08 UTC, yeegor requested changes
Minor changes required, mostly readability improvements, although some are related to the logic.

2020-10-27 15:32 UTC, robertsbriedis commented on src/app/component/Footer/Footer.component.js
>          if (!isVisibleOnMobile && device.isMobile) {
One checks if its mobile other if we want to show footer on mobile.

2020-10-27 15:34 UTC, robertsbriedis commented on src/app/component/Footer/Footer.component.js
> +    };
Not quite sure, how I could rename it better.

2020-10-28 09:53 UTC, yeegor requested changes
Minor changes requested.

2020-10-28 09:53 UTC, yeegor commented on src/app/component/Footer/Footer.config.js
> +                title: 'Accessories'
Still relevant!

2020-10-28 09:53 UTC, yeegor commented on src/app/util/Media/Media.js
> +    return `${ baseUrl }${ subPath }${ src }`;
Please provide comments on this

2020-10-30 13:50 UTC, alfredsgenkins approved these changes
I think this approach with CMS block or footer styles is interesting, while in real life providing same styles as in your styled footer would be very hard.

2020-10-30 13:50 UTC, merged