SWPWA-1443 - Support for recently viewed products widget
scandipwa/base-theme pull request #1632
Opened 2020-11-06 16:10 UTC by AleksandrsKondratjevs

2020-11-10 14:58 UTC, alfredsgenkins requested changes
Also please update composer dependency to this module version: https://github.com/scandipwa/cms-graphql/releases/tag/1.4.2

2020-11-10 14:58 UTC, alfredsgenkins commented on src/app/route/ProductPage/ProductPage.container.js
> +        updateRecentlyViewedProducts(newRecentProducts);
I think this logic part may be moved to the reducer

2020-11-10 14:58 UTC, alfredsgenkins commented on src/app/route/ProductPage/ProductPage.container.js
> +            product, product: { sku: newSku },
Move this to new line each if it stays.

2020-11-10 14:58 UTC, alfredsgenkins commented on src/app/component/RecentlyViewedWidget/RecentlyViewedWidget.component.js
> +                )) }
Let's split this into another function

2020-11-12 15:55 UTC, yeegor approved these changes
Overall seems legit

2020-11-12 15:55 UTC, yeegor commented on src/app/component/RecentlyViewedWidget/RecentlyViewedWidget.config.js
> +export const RECENTLY_VIEWED_PRODUCTS = 'recentlyViewedProducts';
Prefer:
```js
export const RECENTLY_VIEWED_PRODUCTS = 'RECENTLY_VIEWED_PRODUCTS';
```

2020-11-12 16:00 UTC, merged