#1650 Hide empty attributes. Textarea, media_image support
scandipwa/base-theme pull request #1669
Opened 2020-11-12 09:34 UTC by riha112

Original issue: #1650 
## Issue requirements:
Don't need show these attributes:
- empty
- we see in another place (short description, URL and etc)

## In this PR:
- Some values where empty due to unsupported attribute types: "textarea", "media_image", thus I added support for rendering.
- Removed from displaying attributes with: "null" or empty values.

## How to remove attributes from product information:
There was no need to implement support for removal of repeating product attributes in PDP as they can be disabled in BE admin panel: _Stores -> attributes -> Product -> [Select specific_attribute] -> StoreFront Properties -> Used in product listing -> No_

2020-11-17 08:28 UTC, zans-laksa reviewed
Code review passed

2020-11-19 14:19 UTC, alfredsgenkins requested changes

2020-11-19 14:19 UTC, alfredsgenkins commented on src/app/component/ProductInformation/ProductInformation.component.js
> +    renderAttribute = ([attributeLabel, valueLabel]) => (!this.isEmpty(valueLabel) && !this.isEmpty(attributeLabel) ? (
Please do it with normal if's. No conditional rendering!

2020-11-20 11:44 UTC, riha112 commented
Due to lost Repository moving to new PR: https://github.com/scandipwa/base-theme/pull/1742

2020-11-20 11:44 UTC, closed without merging