WGB-184 Image zoom
scandipwa/base-theme pull request #817
Opened 2020-08-03 09:39 UTC by ErnestsVerins

2020-09-28 13:15 UTC, yeegor requested changes
I went through the coding style and it needs improvement.

@alfredsgenkins I am not aware of what this actually is, I see the vertical scrollable gallery references from VGB, is this PR relevant?

2020-09-28 13:15 UTC, yeegor commented on src/app/component/ProductGallery/ProductGallery.container.js
> +                        { ...this.containerFunctions }
Wrong spacing here. JSX nesting considers 2 space indent, blocks - 4 space.

2020-09-28 13:15 UTC, yeegor commented on src/app/component/ProductGallery/ProductGallery.container.js
> +export default connect(null,mapDispatchToProps)(ProductGalleryContainer);
Spacing after comma is required.

2020-09-28 13:15 UTC, yeegor commented on src/app/component/ProductGallery/ProductGallery.style.scss
> +        & nav {
Consider adding paddings to blocks

2020-09-28 13:15 UTC, yeegor commented on src/app/component/Slider/Slider.component.js
> +                onClick={ () => this.changeActiveImage(i) }
Wrong indentation in all the JSX.

2020-09-28 13:15 UTC, yeegor commented on src/public/assets/images/global/search.svg
> +<?xml version="1.0" encoding="iso-8859-1"?>
I believe that both search and arrow icons are implemented as CSS in the ScandiPWA core.

2020-11-03 15:28 UTC, alfredsgenkins commented
Closing, we took a different implementation. Thanks for contribution tho!

2020-11-03 15:28 UTC, closed without merging