Remove add to home screen button for firefox/opera
scandipwa/base-theme pull request #899
Opened 2020-08-28 11:45 UTC by danielsstabulis

2020-08-28 12:37 UTC, alfredsgenkins requested changes

2020-08-28 12:37 UTC, alfredsgenkins commented on src/app/util/Mobile/isMobile.js
> +    any: () => (isMobile.android() || isMobile.blackBerry() || isMobile.iOS() || isMobile.opera() || isMobile.windows() || isMobile.vanillaOpera() || isMobile.firefox()),
This will actually break mobile check on opera and safari. Please don't add this here, keep only `vanillaOpera` and `firefox` in the list.

2020-09-28 14:49 UTC, yeegor commented
Why is this necessary? Isn't it possible to implement this functionality so that it works on all the mobile browsers?

2020-11-03 15:27 UTC, alfredsgenkins commented
Closing, the Yegors is right, there must be a better way for this.

2020-11-03 15:27 UTC, closed without merging