remove user agent from isMobile
scandipwa/base-theme pull request #988
Opened 2020-09-16 15:16 UTC by ejnshtein

#716 Fix

2020-09-16 15:21 UTC, ejnshtein commented
Currently unable to test new behavior on iPhone and iPad in Chrome Devtools.
The client hints return empty values.
<img width="1535" alt="Screenshot 2020-09-16 at 18 19 30" src="https://user-images.githubusercontent.com/18352350/93357611-2c6f1580-f849-11ea-98a4-7d0f5fd87725.png">
 
However, Pixel 2 emulation works properly.
<img width="1511" alt="Screenshot 2020-09-16 at 18 20 23" src="https://user-images.githubusercontent.com/18352350/93357707-4c063e00-f849-11ea-8255-bc7f0eadf4de.png">

2020-09-18 12:00 UTC, yeegor requested changes

2020-09-18 12:14 UTC, ejnshtein commented on src/app/store/Config/Config.action.js
> +/** @namespace Store/Config/Action/updateDeviceConfig */
Should I use UPDATE_CONFIG_DEVICE then?

2020-09-18 12:15 UTC, ejnshtein commented on src/app/store/Config/Config.reducer.js
> +        mobile: true,
Done.

2020-09-18 14:27 UTC, ejnshtein commented on src/app/component/MenuItem/MenuItem.component.js
> +            || (!device.isMobile && !isBanner && !isLogo)
Yeah, will add it.

2020-09-18 15:36 UTC, yeegor approved these changes

2020-09-18 16:15 UTC, yeegor requested changes
Clicking related products on PDP breaks the application on mobile (tested on Chrome on Pixel 2 XL, emulated with my mac)

2020-09-18 16:52 UTC, ejnshtein commented
Should be fixed now

2020-09-21 06:53 UTC, yeegor commented on src/app/store/Config/Config.action.js
> +/** @namespace Store/Config/Action/updateDeviceConfig */
It should be updateDevice

2020-09-21 06:55 UTC, yeegor commented on src/app/component/Router/Router.container.js
> +    componentWillUnmount() {
It's been decided that this logic is going to be moved to a separate component

2020-09-21 07:18 UTC, yeegor approved these changes
All the issues are fixed

2020-09-21 07:19 UTC, yeegor commented
Remember to reference the issue your PR fixes by: Resolves #716

2020-09-21 07:20 UTC, merged