[#888] Adding multiple address fields functionality
scandipwa/base-theme pull request #990
Opened 2020-09-16 20:58 UTC by MaksimGritcenko

https://github.com/scandipwa/base-theme/issues/888

2020-09-17 09:17 UTC, MaksimGritcenko commented
BE part for this issue scandipwa/store-graphql#6

2020-09-17 12:00 UTC, yeegor requested changes

2020-09-17 14:01 UTC, MaksimGritcenko commented on src/app/component/CheckoutBilling/CheckoutBilling.container.js
> +        const address = this._getAddress(addressLinesQty > 1
I don`t handle this comparison in this function.

2020-09-18 16:46 UTC, yeegor requested changes

2020-09-18 16:46 UTC, yeegor commented on src/app/util/Address/index.js
> +    const newFields = Object.keys(fields)
Please comment this

2020-09-18 16:46 UTC, yeegor commented on src/app/component/CheckoutBilling/CheckoutBilling.container.js
> +            ? setAddressesInFormObject(fields, addressLinesQty)
I believe this logic should be a part of _getAddress function

2020-09-18 16:46 UTC, yeegor commented on src/app/component/CheckoutShipping/CheckoutShipping.container.js
> +            : trimAddressFields(addressLinesQty > 1 ? setAddressesInFormObject(fields, addressLinesQty) : fields);
This is poorly readable, please split the function call with argument selection

2020-09-18 16:46 UTC, yeegor commented on src/app/component/MyAccountAddressForm/MyAccountAddressForm.component.js
> +    getAddressFields() {
Please comment on why this function is necessary

2020-09-28 15:00 UTC, yeegor requested changes
Overall OK, but please introduce changes corresponding to the comments I have left.

2020-09-28 15:00 UTC, yeegor commented on src/app/component/CheckoutShipping/CheckoutShipping.container.js
> +        const formFields = addressLinesQty > 1
I believe this logic can be hidden in "getFormFields" function with the only responsibility of handling this logic.
Please use this approach in order to get rid of the ternary operator and to make code more readable.

2020-09-28 15:00 UTC, yeegor commented on src/app/component/CheckoutBilling/CheckoutBilling.container.js
> +            ? setAddressesInFormObject(fields, addressLinesQty)
Read the comment below about the same logic.

2020-09-29 12:29 UTC, MaksimGritcenko commented on src/app/util/Address/index.js
> +    const newFields = Object.keys(fields)
but there are related fields. They just need to get transformed into a single array

2020-10-06 11:40 UTC, merged